export const EMPTY_STOP_FILTER = ["==", ["get", "id"], "__none__"] as const;
export const EMPTY_LINE_FILTER = ["==", ["get", "line_id"], "__none__"] as const;
export const EMPTY_VEHICLE_FILTER = ["==", ["get", "vehicle_id"], "__none__"] as const;

export function roadColorExpression(): unknown[] {
  return [
    "match",
    ["get", "road_class"],
    "motorway",
    "#6f7984",
    "motorway_link",
    "#7c8692",
    "trunk",
    "#7b8795",
    "trunk_link",
    "#87929e",
    "primary",
    "#8d99a8",
    "primary_link",
    "#98a3af",
    "secondary",
    "#a1abb6",
    "secondary_link",
    "#aeb7bf",
    "tertiary",
    "#b4bcc3",
    "tertiary_link",
    "#bcc3c9",
    "#c9d0d6",
  ];
}

export function roadWidthExpression(): unknown[] {
  return [
    "interpolate",
    ["linear"],
    ["zoom"],
    6.5,
    [
      "match",
      ["get", "road_class"],
      "motorway",
      1.3,
      "motorway_link",
      1.0,
      "trunk",
      1.15,
      "trunk_link",
      0.85,
      "primary",
      0.95,
      "primary_link",
      0.72,
      "secondary",
      0.45,
      "secondary_link",
      0.35,
      "tertiary",
      0.3,
      "tertiary_link",
      0.28,
      "unclassified",
      0.25,
      "residential",
      0.22,
      "living_street",
      0.18,
      "service",
      0.16,
      "pedestrian",
      0.14,
      0.2,
    ],
    12,
    [
      "match",
      ["get", "road_class"],
      "motorway",
      2.8,
      "motorway_link",
      2.0,
      "trunk",
      2.3,
      "trunk_link",
      1.7,
      "primary",
      1.9,
      "primary_link",
      1.4,
      "secondary",
      1.25,
      "secondary_link",
      0.95,
      "tertiary",
      0.9,
      "tertiary_link",
      0.8,
      "unclassified",
      0.7,
      "residential",
      0.62,
      "living_street",
      0.52,
      "service",
      0.45,
      "pedestrian",
      0.42,
      0.55,
    ],
    15,
    [
      "match",
      ["get", "road_class"],
      "motorway",
      5.0,
      "motorway_link",
      3.8,
      "trunk",
      4.2,
      "trunk_link",
      3.2,
      "primary",
      3.4,
      "primary_link",
      2.6,
      "secondary",
      2.4,
      "secondary_link",
      1.9,
      "tertiary",
      1.8,
      "tertiary_link",
      1.5,
      "unclassified",
      1.3,
      "residential",
      1.15,
      "living_street",
      0.95,
      "service",
      0.85,
      "pedestrian",
      0.8,
      1.0,
    ],
  ];
}

export function roadCasingWidthExpression(): unknown[] {
  return [
    "interpolate",
    ["linear"],
    ["zoom"],
    6.5,
    [
      "match",
      ["get", "road_class"],
      "motorway",
      1.76,
      "motorway_link",
      1.35,
      "trunk",
      1.55,
      "trunk_link",
      1.15,
      "primary",
      1.28,
      "primary_link",
      0.97,
      "secondary",
      0.61,
      "secondary_link",
      0.47,
      "tertiary",
      0.41,
      "tertiary_link",
      0.38,
      "unclassified",
      0.34,
      "residential",
      0.3,
      "living_street",
      0.24,
      "service",
      0.22,
      "pedestrian",
      0.19,
      0.27,
    ],
    12,
    [
      "match",
      ["get", "road_class"],
      "motorway",
      3.78,
      "motorway_link",
      2.7,
      "trunk",
      3.11,
      "trunk_link",
      2.3,
      "primary",
      2.57,
      "primary_link",
      1.89,
      "secondary",
      1.69,
      "secondary_link",
      1.28,
      "tertiary",
      1.22,
      "tertiary_link",
      1.08,
      "unclassified",
      0.94,
      "residential",
      0.84,
      "living_street",
      0.7,
      "service",
      0.61,
      "pedestrian",
      0.57,
      0.74,
    ],
    15,
    [
      "match",
      ["get", "road_class"],
      "motorway",
      6.75,
      "motorway_link",
      5.13,
      "trunk",
      5.67,
      "trunk_link",
      4.32,
      "primary",
      4.59,
      "primary_link",
      3.51,
      "secondary",
      3.24,
      "secondary_link",
      2.57,
      "tertiary",
      2.43,
      "tertiary_link",
      2.03,
      "unclassified",
      1.76,
      "residential",
      1.55,
      "living_street",
      1.28,
      "service",
      1.15,
      "pedestrian",
      1.08,
      1.35,
    ],
  ];
}

export function localRoadOpacityExpression(): unknown[] {
  return ["interpolate", ["linear"], ["zoom"], 6.5, 0.35, 10, 0.62, 13.5, 0.95];
}

export function localRoadFilter(): unknown[] {
  return ["==", ["get", "feature_layer"], "road"];
}

export function railFilter(): unknown[] {
  return ["==", ["get", "feature_layer"], "rail"];
}

export function waterFilter(): unknown[] {
  return ["==", ["get", "feature_layer"], "water"];
}

export function landuseFilter(): unknown[] {
  return ["==", ["get", "feature_layer"], "landuse"];
}
